// Demo data so every screen renders meaningfully out of the box.
// Replace each of these with real Supabase queries — see the
// `// SUPABASE:` comments throughout the page components for the
// exact query to swap in.

import { Appointment, Department, Doctor, Hospital, QueueTicket } from "./types";

export const mockHospitals: Hospital[] = [
  {
    id: "h1",
    name: "مستشفى النور التخصصي",
    slug: "al-noor",
    city: "الرياض",
    district: "العليا",
    address: "شارع الملك فهد",
    phone: "0114001000",
    rating: 4.6,
    rating_count: 812,
    open_24h: true,
    status: "active",
    departments_count: 8,
    doctors_count: 42,
  },
  {
    id: "h2",
    name: "مستشفى الشفاء العام",
    slug: "al-shifa",
    city: "جدة",
    district: "الروضة",
    address: "شارع فلسطين",
    phone: "0126002000",
    rating: 4.3,
    rating_count: 540,
    open_24h: false,
    status: "active",
    departments_count: 6,
    doctors_count: 27,
  },
  {
    id: "h3",
    name: "مجمع الرعاية الأولى",
    slug: "primary-care",
    city: "الرياض",
    district: "الملقا",
    address: "طريق الملك عبدالله",
    phone: "0114003000",
    rating: 4.8,
    rating_count: 301,
    open_24h: false,
    status: "active",
    departments_count: 5,
    doctors_count: 15,
  },
];

export const mockDepartments: Department[] = [
  { id: "d1", hospital_id: "h1", name: "الباطنية", name_en: "Internal Medicine", icon: "stethoscope", avg_consultation_minutes: 15, doctors_count: 6 },
  { id: "d2", hospital_id: "h1", name: "الأطفال", name_en: "Pediatrics", icon: "baby", avg_consultation_minutes: 12, doctors_count: 5 },
  { id: "d3", hospital_id: "h1", name: "الجلدية", name_en: "Dermatology", icon: "sparkles", avg_consultation_minutes: 15, doctors_count: 3 },
  { id: "d4", hospital_id: "h1", name: "القلب", name_en: "Cardiology", icon: "heart-pulse", avg_consultation_minutes: 20, doctors_count: 4 },
  { id: "d5", hospital_id: "h1", name: "العظام", name_en: "Orthopedics", icon: "bone", avg_consultation_minutes: 20, doctors_count: 4 },
];

export const mockDoctors: Doctor[] = [
  {
    id: "doc1",
    profile_id: "p1",
    hospital_id: "h1",
    department_id: "d1",
    full_name: "د. سارة الحربي",
    title: "استشارية",
    specialty: "الباطنية",
    bio: "استشارية باطنية بخبرة تفوق ١٥ عامًا في تشخيص وعلاج أمراض الجهاز الهضمي والغدد الصماء.",
    years_experience: 15,
    consultation_fee: 250,
    avg_consultation_minutes: 15,
    rating: 4.9,
    rating_count: 214,
    is_active: true,
    hospital_name: "مستشفى النور التخصصي",
    department_name: "الباطنية",
    next_available: "اليوم، ٤:٣٠ م",
  },
  {
    id: "doc2",
    profile_id: "p2",
    hospital_id: "h1",
    department_id: "d2",
    full_name: "د. خالد العتيبي",
    title: "أخصائي",
    specialty: "طب الأطفال",
    bio: "أخصائي طب أطفال، مهتم برعاية حديثي الولادة والتطعيمات.",
    years_experience: 9,
    consultation_fee: 180,
    avg_consultation_minutes: 12,
    rating: 4.7,
    rating_count: 156,
    is_active: true,
    hospital_name: "مستشفى النور التخصصي",
    department_name: "الأطفال",
    next_available: "غدًا، ٩:٠٠ ص",
  },
  {
    id: "doc3",
    profile_id: "p3",
    hospital_id: "h2",
    department_id: "d4",
    full_name: "د. منى القحطاني",
    title: "استشارية",
    specialty: "أمراض القلب",
    bio: "استشارية قلب وأوعية دموية، حاصلة على الزمالة الأمريكية لأمراض القلب.",
    years_experience: 18,
    consultation_fee: 320,
    avg_consultation_minutes: 20,
    rating: 4.9,
    rating_count: 301,
    is_active: true,
    hospital_name: "مستشفى الشفاء العام",
    department_name: "القلب",
    next_available: "اليوم، ٦:٠٠ م",
  },
  {
    id: "doc4",
    profile_id: "p4",
    hospital_id: "h1",
    department_id: "d3",
    full_name: "د. فهد الدوسري",
    title: "أخصائي",
    specialty: "الجلدية",
    bio: "أخصائي جلدية وليزر، مهتم بالأمراض الجلدية المزمنة والتجميل الطبي.",
    years_experience: 7,
    consultation_fee: 220,
    avg_consultation_minutes: 15,
    rating: 4.5,
    rating_count: 98,
    is_active: true,
    hospital_name: "مستشفى النور التخصصي",
    department_name: "الجلدية",
    next_available: "الخميس، ١١:٠٠ ص",
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: "a1",
    patient_id: "pt1",
    patient_name: "عبدالرحمن السالم",
    hospital_id: "h1",
    hospital_name: "مستشفى النور التخصصي",
    department_id: "d1",
    department_name: "الباطنية",
    doctor_id: "doc1",
    doctor_name: "د. سارة الحربي",
    appointment_date: "2026-07-28",
    scheduled_time: "16:30",
    status: "checked_in",
    priority: "normal",
    reason: "متابعة نتائج تحاليل",
  },
  {
    id: "a2",
    patient_id: "pt1",
    patient_name: "عبدالرحمن السالم",
    hospital_id: "h2",
    hospital_name: "مستشفى الشفاء العام",
    department_id: "d4",
    department_name: "القلب",
    doctor_id: "doc3",
    doctor_name: "د. منى القحطاني",
    appointment_date: "2026-08-02",
    scheduled_time: "18:00",
    status: "booked",
    priority: "normal",
  },
  {
    id: "a3",
    patient_id: "pt1",
    patient_name: "عبدالرحمن السالم",
    hospital_id: "h1",
    hospital_name: "مستشفى النور التخصصي",
    department_id: "d2",
    department_name: "الأطفال",
    doctor_id: "doc2",
    doctor_name: "د. خالد العتيبي",
    appointment_date: "2026-06-14",
    scheduled_time: "09:00",
    status: "completed",
    priority: "normal",
  },
  {
    id: "a4",
    patient_id: "pt2",
    patient_name: "منيرة الشمري",
    hospital_id: "h1",
    hospital_name: "مستشفى النور التخصصي",
    department_id: "d1",
    department_name: "الباطنية",
    doctor_id: "doc1",
    doctor_name: "د. سارة الحربي",
    appointment_date: "2026-07-29",
    scheduled_time: "17:00",
    status: "booked",
    priority: "elderly",
  },
  {
    id: "a5",
    patient_id: "pt3",
    patient_name: "سعود الغامدي",
    hospital_id: "h1",
    hospital_name: "مستشفى النور التخصصي",
    department_id: "d1",
    department_name: "الباطنية",
    doctor_id: "doc1",
    doctor_name: "د. سارة الحربي",
    appointment_date: "2026-07-29",
    scheduled_time: "17:15",
    status: "booked",
    priority: "normal",
  },
];

export const mockQueueToday: QueueTicket[] = [
  { id: "q1", appointment_id: "a10", hospital_id: "h1", doctor_id: "doc1", queue_date: "2026-07-28", queue_number: 40, status: "done", priority: "normal", estimated_wait_minutes: 0, patient_name: "عبدالله المطيري" },
  { id: "q2", appointment_id: "a11", hospital_id: "h1", doctor_id: "doc1", queue_date: "2026-07-28", queue_number: 41, status: "done", priority: "elderly", estimated_wait_minutes: 0, patient_name: "منيرة الشمري" },
  { id: "q3", appointment_id: "a12", hospital_id: "h1", doctor_id: "doc1", queue_date: "2026-07-28", queue_number: 42, status: "in_progress", priority: "normal", estimated_wait_minutes: 0, patient_name: "سعود الغامدي" },
  { id: "q4", appointment_id: "a1", hospital_id: "h1", doctor_id: "doc1", queue_date: "2026-07-28", queue_number: 43, status: "called", priority: "pregnant", estimated_wait_minutes: 0, patient_name: "ريم الحارثي" },
  { id: "q5", appointment_id: "a13", hospital_id: "h1", doctor_id: "doc1", queue_date: "2026-07-28", queue_number: 44, status: "waiting", priority: "normal", estimated_wait_minutes: 15, patient_name: "تركي العنزي" },
  { id: "q6", appointment_id: "a14", hospital_id: "h1", doctor_id: "doc1", queue_date: "2026-07-28", queue_number: 45, status: "waiting", priority: "emergency", estimated_wait_minutes: 30, patient_name: "لطيفة القرني" },
  { id: "q7", appointment_id: "a15", hospital_id: "h1", doctor_id: "doc1", queue_date: "2026-07-28", queue_number: 46, status: "waiting", priority: "normal", estimated_wait_minutes: 45, patient_name: "بندر العصيمي" },
];
